#!/bin/bash
# Wrapper for cargo that first generates Cargo.toml from Cargo.toml.in, deriving crate version
# from the most recent git tag, which must be SemVer-formatted (vX.Y.Z).
set -e
cd `dirname $0`

revision="$(git describe --tags --dirty)"
revision="${revision#v}"  # strip 'v' prefix

sed "s/{{GIT_SEMVER}}/${revision}/" Cargo.toml.in > Cargo.toml

# picked up by rusqlite[bundled]
# https://www.sqlite.org/compile.html
export LIBSQLITE3_FLAGS='
    SQLITE_ENABLE_LOAD_EXTENSION
    SQLITE_USE_URI
    SQLITE_LIKE_DOESNT_MATCH_BLOBS
    SQLITE_DEFAULT_MEMSTATUS=0
    SQLITE_MAX_EXPR_DEPTH=0
    SQLITE_ENABLE_NULL_TRIM
    SQLITE_USE_ALLOCA
    SQLITE_HAVE_ISNAN
    SQLITE_ENABLE_UPDATE_DELETE_LIMIT
    SQLITE_ENABLE_COLUMN_METADATA
    SQLITE_ENABLE_DBSTAT_VTAB
    SQLITE_ENABLE_PREUPDATE_HOOK
    SQLITE_ENABLE_SESSION
    -USQLITE_DEFAULT_FOREIGN_KEYS
    -USQLITE_ENABLE_API_ARMOR
    -USQLITE_ENABLE_JSON1
    -USQLITE_ENABLE_FTS3
    -USQLITE_ENABLE_FTS3_PARENTHESIS
    -USQLITE_ENABLE_FTS5
    -USQLITE_ENABLE_RTREE
    -USQLITE_SOUNDEX
    -USQLITE_ENABLE_MEMORY_MANAGEMENT
    -USQLITE_ENABLE_PREUPDATE_HOOK
    -USQLITE_ENABLE_SESSION
'
cargo "$@"
